[package]
name = "advent_2021"
version = "0.1.0"
edition = "2021"
authors = ["DeltaManiac <maxpaynered@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.10.1"
nalgebra = "0.29.0"
aoc-main = "0.3.0"
